services:
  db:
    container_name: gutensearch-db
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: gutensearch
    ports:
      - 3307:3306
    volumes:
      - gutensearch-db-data:/var/lib/mysql

volumes:
  gutensearch-db-data:
